RhinoSecurityLabs/pacu

modules/aws__enum_spend/main.py
pacu.py

When there's more than about 40 services used, the output of the aws__enum_spend module can exceed the pacu-defined 1000 character limit and die.  
This patch raises the limit to 10,000 characters, formats the output into columns, and sorts the output by amount spent in descending order.

Fixing aws__enum_spend when account uses too many services

---

modules/iam__bruteforce_permissions/main.py

Allows for bruteforce enumeration to include cloudwatch logs api.
A common mistake for lambda function roles is to include * for cloudwatch logs permissions as the lambda function name determines cloudwatch log group. If lambda function leaks credentials this is useful for detecting services that are likely to be "open".

Add cloudwatch logs enumeration to iam__bruteforce_permissions module

---

modules/ec2__download_userdata/main.py

As requested in #136 tag filtering has been added to ec2__download_userdata. Tags can be filtered by tag key, tag value, or both. 
closes #136

Added tag filtering

---

pacu.py

This will catch sqlalchemy errors. Often these errors are caused by changes to the db model. Updates to the db model can invalidate the preexisting db file. 
fixes #124

Added error message for sqlalchemy

---

modules/iam__enum_roles/default-word-list.txt

This role is provisioned automatically by AWS when an account is joined to an AWS organization, so it can be a quick win in a lot of situations. c.f. https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts_access.html
> If you create an account by using the tools provided as part of AWS Organizations, you can access the account by using the preconfigured role named OrganizationAccountAccessRole that exists in all new accounts that are created this way.

Add 'OrganizationAccountAccessRole' to roles enumeration wordlist

---

modules/ec2__download_userdata/main.py

This replaces byte comparison which was improperly implemented with try/except blocks to attempt to decode Gzip compressed userdata in the ec2__download_userdata module.

Fix GZIP decoding problems in ec2__download_userdata

---

pacu.py

This PR fixes the list command allowing the use of `list cat/egory` to view a list of categories and `list cat/egory enum` to view the modules from a specific category. In the process of fixing this command, I found that there was no centralized list of categories and a single hardcoded list was being used. To fix this I wrote a new function `load_categories()` to load all categories on run.

Fix list category

---

modules/iam__enum_permissions/main.py

Running `run iam__enum_permissions --all-users --all-roles` when a policy contains a NotResource action will cause it to fail.
This just prevents Pacu from erroring out when it can likely complete the rest of the polices. There's likely other code path's this will happen on but I'm not able to test those at the moment, think we'll just have to fix them as they come up, or until we can rewrite this code.
Fixes #224

Minimal fix when enumerating NotResource

---

requirements-dev.txt
requirements.txt

typing-extensions is not listed in requirements.txt causing Pacu to crash after installing. Added the dep to be installed on setup. 
Fixes issue #233

Adding typing-extensions dep

---

modules/iam__privesc_scan/main.py

This adds PassExistingRoleToNewLambdaThenInvokeCrossAccount which is similar to PassExistingRoleToNewLambdaThenInvoke but with with lambda:AddPermission instead of lambda:InvokeFunction.

Add PassExistingRoleToNewLambdaThenInvokeCrossAccount

---

modules/enum__apigateway/main.py

The module starts by looping over all available APIs. For each API it will enumerate the available routes, methods, authentication, and associated services like Lambda. The module will then attempt to enumerate available API keys and client certificates. Finally, the module will attempt to export the definitions as swagger files. 
All results including the swagger exports will be saved to the session's download file. 
The module does not support HTTP or WebsocketAPI types. These types use the boto3 library "apigatewayv2" and use and different methods and response structures. I currently don't plan on adding support for these types.

API Gateway Enumeration Module 

---

core/mixins.py
modules/ecs__enum_task_def/main.py
utils.py

The datetime object in the ecs task def response causes serialization to fail without setting a default method.
This change sets the default to str.

Fix ecs__enum_task_def datetime serialization

---

pacu/modules/iam__enum_permissions/main.py

iam__enum_permissions used `GetUser` API to get a username, but sometime the user doesn't have a `GetUser` permission
```python
client = pacu_main.get_boto3_client('iam')
try:
user = client.get_user()
active_aws_key.update(
pacu_main.database,
user_name=user['User']['UserName'],
arn=identity['Arn'],
user_id=identity['UserId'],
account_id=identity['Account']
)
````
This pull request will extract username from user's ARN

fix iam__enum_permissions can't determine current user (#226)

---

pacu/main.py

It's more convenient if 'data' command accepts both upper case and lower case services name

Added 'data' command accepts case insensitive service name

---

pacu/main.py
tests/test_pacu_session.py

https://github.com/RhinoSecurityLabs/pacu/blob/21cd33759870a5f84a2380cd94ab1ec2dcaed823/pacu/main.py#L688-L694
#260 has a bug when some service name didn't use all upper case latter
```
APIGateway      CloudTrail      CloudWatch      CodeBuild
```

Fix bug data command not found some service and improve minor UX.

---

pacu/modules/iam__enum_permissions/main.py

I noticed that `run iam__privesc_scan --offline` was only reporting on roles and not users.  Digging into it, I realized that user json files were not getting written to  `~.local/share/pacu/test/downloads/confirmed_permissions/` when `iam__enum_permissions` is run with the `--all-users` flag, while the roles.json files were getting written.  
It looks like the only difference is this `session.name`. Once I removed it, everything worked as expected.  I ran `run iam__enum_permissions --all-users` and the user json files were written at which point `run iam__privesc_scan --offline` reported on both users and roles.  Easy fix for my use case, but I haven't done any other testing to see if this breaks something else.

Fix for users.json files not getting populated

---

Dockerfile.dev
Makefile
pacu/modules/cfn__resource_injection/cfn__resource_injection_lambda/app.py
pacu/modules/cfn__resource_injection/cfn__resource_injection_lambda/tests/test_app.py
poetry.lock
pyproject.toml
requirements-dev.txt

* Bump version to v1.1.0
* Adds the `pacu/modules/cfn__resource_injection/cfn__resource_injection_lambda/tests` tests to run during `make test`.
* Add moto to dev dependencies. 
* Dev requirements are exported without hashes. This was how it was done previously due to an error with colorama during install, thought this was fixed but that doesn't seem to be the case.
* Includes fixes for the dev Dockerfile.
* The shell wasn't using the installed pip dependencies before.

Release v1.1.0, add cfn_resource_injection testing

---

pacu/core/lib.py
pacu/main.py
tests/test_pacu_update.py
tests/test_pacu_utils.py

If install pacu via pip pacu_dir() will return  `/home/user/.local/lib/python3.8/site-packages` 
this PR fix pacu_dir() to return `/home/user/.local/lib/python3.8/site-packages/pacu`
I found this when trying to fixes a bug on #284

fix pacu_dir not return '/home/user/.local/lib/python3.8/pacu'

---

pacu/main.py
tests/test_pacu_data_command.py
tests/test_pacu_session.py

printing all data in the service is too much information. this PR helps you scope which sub-service you want to lookup.
```console
Pacu (session:test) > data ec2 subnets
```

add a data command sub service filter

---

pacu/modules/s3__download_bucket/main.py

Resolves #292 
Ran into the same error with message `write() argument must be str, not bytes`, fixed by specifying both modes in save call.

Add in byte writeable option to fix s3 download

---

pacu/modules/iam__backdoor_assume_role/main.py

This PR addresses https://github.com/RhinoSecurityLabs/pacu/issues/303. In `iam__backdoor_assume_role ` the IAM Boto client gets overwritten with an STS Boto client if a user ARN is not specified. I'm proposing a fix that just uses a different name for the STS client.

Fix for IAM Boto client overwrite bug

---

pacu/core/models.py
pacu/main.py
pacu/settings.py

This PR adds a new command to the interactive Pacu UI that allows a user to set a custom suffix that will be appended to all the user agent sent with all API calls. The intended purpose of this feature is to allow users to tag logs associated with actions they perform with different Pacu sessions.
If the user supplies a specific string, it will be appended along with a space to the end of the user agent. If no string is supplied, it will generate one from a UUID in the form `Pacu-Session-42c018ee-7bf1-4e83-ab83-9d9fdde059d4`.

Support AWS log tagging with custom user agent suffix command

---

pacu/main.py
pacu/modules/cfn__resource_injection/main.py

Currently for the module cfn__resource_injection takes two input
1. s3-access-key : Victims key
2. attacker-key: Attackers key
In the code we are checking if current session is victims key or not and throwing an error. Victims key and Attacker key cannot have same pacu session at same time, we should just check if victims key exists in pacu database and use that as needed.   Function `get_aws_key_by_alias_from_db` checks if give key alias exists in db or not. 
```
Pacu (attack:attack) > run cfn__resource_injection --attacker-key attack --s3-access-key victim 
```

cfn__resource_injection: Wrongly checking session id of victim as current session

---

pacu/core/models.py
pacu/modules/organizations__enum/main.py
requirements.txt

Added module to list AWS Organizations (organizations__enum). This lists overview, root accounts, normal accounts, OUs, and delegated admins. Also added ability to make a graph of AWS Organization hierarchy to make it easier to visualize the account numbers/OUs you are able to pull down. 
Working on Enumeration Module for IdentityStore next for IAM Identity Center, and subsequent lateral movement module for SSO'ing into other accounts which all builds off org enumeration. First fork so let me know if needs any updates 👍

AWS Organizations Enumeration Module

---

pacu/modules/organizations__assume_role/main.py

Added a module for AWS Organizations that will automatically check member accounts for roles to see if you can assume them. This represents lateral movement. As you will see, I was hoping to maybe create a key-set for each success if possible but wasn't sure how to program that into the current framework. At the moment the module just returns a list of roles you can assume. You can also supply a list of account numbers in a file or inline, and same with role names depending on what you want to do.

AWS Organizations - organizations__assume_role initial upload

---

pacu/main.py

Fixes a bug where the the loop when entering a key alias never breaks if the user just presses enter to keep the same value.

Fix no loop break when enter for key alias

---

pacu/main.py
poetry.lock
pyproject.toml

This adds a `jq` command to Pacu to help parsing collected data output.
```
run ec2__enum
jq '.Instances[].InstanceId' ec2
```
This partially handles #181 it makes it easier to parse and filter the data, although does not really make is searchable.

add jq command to parse collected data

---

pacu/modules/route53__enum/main.py

This expands on the existing route53__enum module to include enumeration of Resource Record Sets which include the DNS entries in each zone.
to test:
`run route53__enum`

Expand route53__enum enumeration

---

pacu/modules/iam__privesc_scan/main.py

fix #329
unconfirmed permission do not have keys it appears, they are just a list of permissions.
The bug was reproduced by running:
```
iam__bruteforce_permissions
iam__privesc_scan
```

fix #329 key error issue with iam__privesc_scan

---

.github/workflows/python-deploy-pypi.yml

the pacu version is not expanded into the docker files when workflow runs, this should fix it.

Make pacu version expand in workflow for docker version

---

pacu/main.py

What I hope is an overall improvement on how credentials are handled and imported in Pacu. Should make life easier.
- Fixes #273.
- Refreshes credentials automatically after importing from a profile with `import_keys`
- Allows importing system default AWS credentials by running `import_keys` with no args.
- Allows option for importing system default AWS credentials if you try to run a module without ever setting keys
- Refreshes system default creds automatically if used.

improve credential handling

---

pacu/core/secretfinder/regexs.json

as this algorithm is getting more popular and being suggested (eg: by github) https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key
Issue #396

Added ed25519 private key pattern on regexs.json for secret finder functionality

---

pacu/modules/ebs__download_snapshots/main.py

When running ```ebs__download_snapshots``` the user will encounter an error because the output directory is not created yet. This fix will check if the directory exists and if not, create the directory allowing the command to succeed. 
Current error message:
```
<class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/home/[user]/.local/share/pacu/[aws-user]/downloads/ebs/snapshots/snap-0c241b0d00d234853.img'```

Fix an error in ebs__download_snapshots

---

pacu/modules/systemsmanager__rce_ec2/main.py

When providing an invalidly formatted `target-instances`, `systemsmanager__rce_ec2` crashes with a python error instead of providing useful feedback to the user. This PR fixes that to ensure parsing of the values returns an expected size (value).
```
Pacu (example:example) > run systemsmanager__rce_ec2 --target-instances "i-11a11a1a111111a11" --command "whoami" --ip-name "arn:aws:iam::1111111111:example"
Running module systemsmanager__rce_ec2...
[2024-05-17 17:23:47] Pacu encountered an error while running the previous command. Check /home/user/.local/share/pacu/example/error_log.txt for technical details. [LOG LEVEL: MINIMAL]
<class 'ValueError'>: not enough values to unpack (expected 2, got 1)
```
```
Pacu (example:example) > run systemsmanager__rce_ec2 --target-instances …
```

Validate target-instances for systemsmanager__rce_ec2

---

pacu/modules/systemsmanager__rce_ec2/main.py

Gracefully handle an access denied error when `get_policy` fails (AccessDenied), and give the user a suggestion on how to fix it.  I left the original bubbled up error message in there as it gives additional context that could help a user debug, but felt the suggestion of manually setting an `ip-name` is a good tip (it got the module to run for me).
```
Pacu (example:example) > run systemsmanager__rce_ec2 --target-instances "i-11a11a1a111111a11" --command "whoami" --ip-name "arn:aws:iam::1111111111:example"
Running module systemsmanager__rce_ec2...
[2024-05-17 17:26:06] Pacu encountered an error while running the previous command. Check /home/cb7192/.local/share/pacu/thomas/error_log.txt for technical details. [LOG LEVEL: MINIMAL]
<class 'botocore.exceptions.ClientError'>: An error …
```

 Add error handling to get_policy in systemsmanager__rce_ec2

---

Dockerfile

This updates the install method in the Dockerfile for aws-cli so that it works.

Fix aws-cli install in Dockerfile, breaking workflows

---

pacu/modules/iam__decode_accesskey_id/main.py

categories are always UPPERCASE. `iam__decode_accesskey_id` seems to be a one off, which is causing it to get its own menu heading when `ls` is run, instead of being with the rest.
(second from the bottom)

fix iam__decode_accesskey_id category

---

pacu/modules/secrets__enum/main.py

All modules seem to use the naming scheme of `component__action`. However, `enum__secrets` seems to be the opposite. This PR changes the name to conform to the rest of the framework.

change enum__secrets to secrets__enum

---

pacu/main.py

Fixes #423 
Fixes a bug which prevented the autocomplete feature from knowing about modules.
When generating the list of modules, an incorrect if statement was making no modules appear.  This corrects that logic, and the list now generates.
After the fix, typing `run` command now correctly generates a list of possible module candidates.

Fix module list generation for autocomplete

---

pacu/main.py

Adds a quiet flag for the cli to prevent printing the pacu banner. Similar to metasploit, this can help take up unnecessary space when trying to take screenshots for reports/support. I kept the version printing though as that is likely important.

New Feature: Quiet Flag

---

pacu/modules/iam__enum_permissions/main.py

This PR modifies `iam__enum_permissions` to display unconfirmed permissions, and counts of each.
To start, we have a new user and key entered in to the db.
When running `iam__enum_permissions` for this (limited) user, we get back the following output.
When looking at this output, it looks like the module failed. We have a `FAILURE`, a `FAILURE`, and while it says 'confirmed permissions for ...', nothing is listed like a user would expect, so I assume no permissions were found BUT the query didn't fail.  We move on down to the summary, and we see 0 and 0. So we must not have been able to enumerate.
However, we run a `whoami` and we see we *did* get permissions:
The problem is that these are **unconfirmed** permissions.  However, they were found so the user should be notified of something. …

Enhance iam__enum_permissions w/ unconfirmed and counts

---

pacu/main.py

Make pacu more friendly to users of other frameworks (metasploit) by aliasing `use` to `run` and `exec`

alias use to run/exec

---

pacu/main.py

Some modules when run w/o arguments will have enough defaults to run the module. However, at times the user just wants to see more info about the module, but they may be unsure how to get a normal python `help` menu to appear for that module. While the `help` command exists, this adds another way to launch that vs a module by adding the `-h` flag to the end of the command.
Example:

UX: Add -h to run/exec to display help

---

pacu/main.py
pacu/settings.py

Adds a history command, saved at exit (not `ctr+c`, assuming that's a bail at all costs method) and loaded at startup. Saved across sessions.

UX: history command

---

pacu/modules/iam__enum_permissions/main.py

When a user runs "iam__enum_permissions", the module provides them with an overview of permissions in this format:
```
[iam__enum_permissions] MODULE SUMMARY:
11 Confirmed permissions for user: cg-sns-user-sns_secrets_cgid01anefb2lz.
0 Confirmed permissions for 0 role(s).
0 Unconfirmed permissions for 0 user(s).
0 Unconfirmed permissions for 0 role(s).
```
It's likely because I'm a Pacu noob, but it took me some time to figure out how to actually read the permissions it enumerated. This very minor fix will tell the user to type "whoami" to see a detailed list of permissions to save time for noobs like me when first using the module.

- Update iam__enum_permissions module 

---

pacu/main.py

This just adds a debug command so that you can easily dump the error log from within the Pacu shell.

Adds a debug command to view error log

---

pacu/modules/apigateway__enum/main.py

- If the user has "GET" permissions on API Gateways but not the API Keys, the module will still get all the paths/methods/resources rather than failing
- There was no error handling on "all regions" so it would fail. Added error handling so the user can check all regions without issues
- Previously it saved the data to a standalone file, updated this so it stores to the Pacu DB like other modules

Fixed the apigateway__enum module

---

pacu/modules/secrets__enum/main.py

When a user has permission to list secrets, but not read them, the output isn't very helpful:
Lots of failures, but no idea what the failures are for. Yes access is denied, but to what?
This PR adds a few print statements to give the user a better idea of what is being probed.

Update secrets_enum to list found secrets

---

pacu/main.py

Personally I prefer to delete some keys as soon as I don't need them anymore just for peace of mind, right now there's no options for that and you need to go directly to the DB or delete the current session 😞
This PR adds a simple `delete_keys` command to delete chosen keys from the current session

Add command to delete AWS keys

---

pacu/main.py

Changes `assume_role` option to allow 2 optional parameters (Serial Number & Token Code) to supply MFA in case this is required to assume a role. 
You can test this on cloudgoat's [iam_privesc_by_key_rotation](https://github.com/RhinoSecurityLabs/cloudgoat/blob/master/scenarios/iam_privesc_by_key_rotation/README.md) scenario

Support for MFA in assume_role
