RhinoSecurityLabs/pacu

pacu.py

added the console/open_console command
It generates a URL to login the current user to the AWS web console

added the console/open_console command

---

pacu.py
requirements.txt

Upgrade SQLAlchemy for windows bug - resolves https://github.com/RhinoSecurityLabs/pacu/issues/153
Add list_sessions/swap_session/delete_session commands

Two updates

---

pacu.py

Fix the "console" command when no creds are set

---

pacu.py

Add "export_keys" command to export your creds to ~/.aws/credentials

Export creds

---

modules/ecr__enum/main.py

This module will pull perform the following functions: 
* Enumerate all the ECR repositories for a given or all regions
* Enumerate all the ECR images for a given or all regions
* Write all results regions to an output file within the 'Downloads' folder for the sessions

Feature_ecr__enum: Added a module to enumerate ECR information within an account for all regions

---

.github/workflows/python-package.yml
README.md

I believe this is the earliest version that may work.

Update python-package.yml to test python 3.6

---

.github/workflows/python-package.yml
Makefile
modules/ebs__download_snapshots/Vagrantfile
modules/ebs__download_snapshots/main.py
modules/ebs__explore_snapshots/main.py
pacu.py
requirements.txt
setup.cfg

> **Downloads User Data from EC2 instances.**
This module will use snapshots discovered when running ebs__enum_volumes_snapshots and prompt you for one to download. Snapshots will be downloaded to ./sessions/<session>/downloads/ebs/snapshots along with a Vagrantfile allowing you to mount the image in a local virtual machine. In order to mount the image you’ll first need to have [vagrant](https://www.vagrantup.com/downloads) and [virtualbox](https://www.virtualbox.org/wiki/Downloads) installed.

Features/ebs  download snapshots

---

modules/cloudformation__download_data/main.py

This module downloads all templates, parameters and outputs from CloudFromation. It parses each as they are downloaded for secrets and outputs any findings.

Module to download CloudFormation data

---

modules/guardduty__list_accounts/main.py

which includes: 
* Lists the organizational member accounts for GuardDuty
* Lists the Guardduty member accounts
* Lists all the Guardduty member accounts

added a new module for guardduty__list_accounts, for determining the lateral movement scope

---

modules/iam__bruteforce_permissions/main.py
modules/iam__bruteforce_permissions/param_generator.py
modules/iam__bruteforce_permissions/preload_actions.json

* Check required params before making the request.
* Resolves #241
* I suspect the change above exposed various broken results so this adds more API specific error code checking to determine if the call was successful or not.
* This ends up getting pretty tedious, may want to see if there's a way to determine this from the botocore model data.
* Handle cases when s3 buckets can't be listed
* Resolves #234 (hopefully)

iam__bruteforce_permissions improvements

---

Dockerfile.dev
modules/iam__enum_roles/main.py
requirements-dev.txt
requirements.txt

* Add's Dockerfile.dev which also installs packages in requirements-dev.txt
* iam__enum_roles improvements
* Rolls back changes on updated role at the end of the run
* If --role-arn isn't passed use a temporary role instead
* Fixes #229
Would be good to start adding tests to some of these, may have to come back to that though.

Dev Dockerfile and iam__enum_roles improvements

---

pacu/modules/cloudwatch__download_logs/main.py
pacu/modules/iam__privesc_scan/main.py
pacu/modules/s3__download_bucket/main.py

Fix the use of `save()` after the packing refactor.

Fix save()

---

pacu/modules/iam__enum_users/main.py

iam__enum_roles has a similar bug as well, I will it fix later

fix #218 iam__enum_users is not adding users to database

---

pacu/modules/lambda__enum/main.py

There are some unused code in module lambda__enum

remove unused code

---

pacu/modules/cloudwatch__download_logs/main.py

fix #212
And I found a type error and include the fix in this PR.

Fix module cloudwatch__download_logs error

---

pacu/modules/cloudwatch__download_logs/main.py

I don't wanna downloads Cloudwatch logs in all regions. That a lot of logs

Add a region argument for module 'cloudwatch__download_logs'

---

pacu/modules/codebuild__enum/main.py

Update main.py for codebuild__enum

---

pyproject.toml

Bumps the patch version for a new pip release.

Release v1.0.4

---

pacu/core/lib.py
pacu/modules/lambda__backdoor_new_roles/main.py

The module used relative path cause bugs when using Pacu from pip 
fix: #284

fix lambda__backdoor_new_roles  path bugs

---

pacu/modules/lambda__backdoor_new_users/main.py

This PR help make it easier if we need to change module related paths.

Simplify lambda_backdoor_new_users paths

---

pacu/main.py

```
Pacu (test:imported-pacu-dev) > swap_session session_name
```

Add swap_session argument

---

pacu/main.py
pacu/modules/iam__bruteforce_permissions/main.py
pacu/modules/lambda__backdoor_new_roles/lambda_function.py.bak
pacu/modules/lambda__backdoor_new_roles/main.py
pacu/modules/lambda__backdoor_new_sec_groups/main.py
pacu/modules/lambda__backdoor_new_users/lambda_function.py.bak
pacu/modules/lambda__backdoor_new_users/main.py

Extend cli: add new session and set AWS keys

Extend cli: add new session and set AWS keys

---

pacu/main.py

Hi! Feature allows to use session keys as profiles in an internal aws command. So if you have active keys, they will be used as default profile when you execute aws command. Also if user has selected 1 region it also will be used as default region in aws command. 
Users can use system aws configs by adding `--profile` flag. For example, `aws --profile default ...` will use default system config. 
Code creates temporary config files and changes environment variables before the run of aws command. As a result aws command uses temporary files as "credentials" config. After execution it deletes all temporary files.

Using session keys as profiles in internal aws command

---

pacu/modules/iam__privesc_scan/main.py

This just adds an enhancement/feature to the iam__privesc_scan module so that you can list privesc methods and print out information about a particular privesc method.

Add privesc method info feature

---

pacu/modules/iam__enum_action_query/main.py

This adds a new module which allows you to query permissions/actions from enumerated permissions.

Module/iam  enum_action_query

---

pacu/main.py

Change session_token to be none when keys are set without one fixes #355

---

pacu/modules/systemsmanager__rce_ec2/main.py

This fixes #309 and some other issues I was seeing. I am still not entirely convinced this fully works as intended or as well as it could. This is probably due for a full rewrite at some point.

Fix #309 and update some functionality

---

pacu/main.py

[Fix](https://github.com/RhinoSecurityLabs/pacu/pull/393/commits/51a9fe6bc298dea017b6d159794562e8e51da8fe) https://github.com/RhinoSecurityLabs/pacu/issues/392

Fixes #392

---

.vscode/launch.json
poetry.toml

Setup environment to debug easily with vscode

Setup vscode debug

---

pacu/modules/ec2__enum/main.py

Fix spelling of public

---

pacu/modules/ecr__enum/main.py

Fix spelling of later

---

pacu/modules/cloudformation__download_data/main.py

Fixes "cloudformation__download_data" module so it properly uses the "--region" flag when passed by the user.

Fixes "cloudformation__download_data" module
